# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_BBS', '0005_auto_20160612_0809'),
        ('WebChat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.IntegerField(choices=[(1, 'single'), (2, 'group')])),
                ('TimeStamp', models.TimeField()),
                ('Content', models.CharField(max_length=100000)),
                ('myself', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_myself', to='Simple_BBS.UserProfile')),
                ('peer_self', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_peer', to='Simple_BBS.UserProfile')),
            ],
        ),
    ]
