# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebChat', '0002_chatrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='TimeStamp',
            field=models.CharField(max_length=200),
        ),
    ]
