# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebChat', '0003_auto_20160616_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='chat_type',
            field=models.CharField(choices=[('single', '单人'), ('group', '群组')], max_length=20),
        ),
    ]
