# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_BBS', '0002_article_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='文章图像'),
        ),
    ]
